### ISSUE TITLE
Changed rock types

### ISSUE THREAD

**Issue by TIle7** [Zylleon/MapDesigner#1]
Hi. 
Great mod.
However, I have an issue.
Tiles I search for contain marble and granite.
But when I use your mod, I get marble and slate. Every time.
Please check.

Also, you have on rock type option. How about two rock types option? And selection of which two?

Also, something about fertility. Vanilla amount is fine, but it seems to change map to map. Drastically. From huge fertile fields to almost none at all.

**Comment by Zylleon** [comment]
Hi, thanks for the feedback!

I can't replicate the marble + slate issue. Which is a shame, since I always look for marble and slate. Try using Prepare Landing to filter tiles with the rock types you wanr.

There are now more options for the number of rock types. Options to pick which rock types are still in progress.

Fertility options are in progress, but will take a while to do properly.

**Comment by TIle7** [comment]
Hi.
I am using prepare landing and initial tile has marble + granite.
But after using you mod and map re roll, I end up with marble and slate.
